package customize;

sub config ( ) {
   my $PBULK_DIR =   '/P/' ;
   my $BULKLOG_DIR = '/P/bulklog';
   return ($PBULK_DIR, $BULKLOG_DIR );
}

sub mail_header($$) {
    my ($OLD_BUILD_START_ISO, $BUILD_START_ISO) = @_;
    my $string = '';
    $string .=  "Subject: diff from ". $OLD_BUILD_START_ISO. ' to '. $BUILD_START_ISO ."\n";
    $string .=  "To: pkgsrc-users\@NetBSD.org\n";
    $string .=  "From: pbulk admin <pkgsrc-users\@NetBSD.org@>\n";
    $string .=  "References: <yfmo93iawb5.wl-makoto\@NetBSD.org>\n";
    $string .=  "MIME-Version: 1.0 (generated by SEMI 1.14.6 - \"Maruoka\")\n";
    $string .=  "Content-Type: text/plain; charset=US-ASCII\n";
    $string .=  "\n";
    return $string;
}
1;
